# Generated by Django 4.0.2 on 2022-03-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersapp', '0002_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emailaddress',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=13),
        ),
    ]
