# Generated by Django 4.0.3 on 2022-03-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
