# Generated by Django 4.0.2 on 2022-04-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Type 3', 'Type 3')], max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('unit_price', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('reorder_level', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Low', 'Low'), ('No Need', 'No Need')], max_length=100, null=True)),
                ('reorder_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
